language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install: "pip install nose coverage python-coveralls"
# command to run tests
script: nosetests -v --with-coverage --cover-package=pyrad
after_success:
  - coveralls
